// // request.setRequestHeader('Cookie', 'POESESSID=52615fa99ef26f7a9ef96bb8bfd81c3b')
//   // http://eteinsetrallume.com/api-stash/index.php?league=heist&tab=1&tabIndex=1&accountName=Toofi
//   // http://localhost:8888/api-stash/index.php?league=heist&tab=1&tabIndex=1&accountName=Toofi

//   // POESESSID :"52615fa99ef26f7a9ef96bb8bfd81c3b"

let initFetch = async () => { 
  let response = await fetch('http://eteinsetrallume.com/api-stash/index.php?league=heist&tab=1&tabIndex=1&accountName=Toofi', {
  method: "GET"});
  let data = await response.json();
  console.log(data);
  return data;
  };

let getAllItems = async () => {
  let tabs = await initFetch();
  let allItems = [];
  for (let i = 0; i < tabs.tabs.length; i++){
    let grab = await fetch(`http://eteinsetrallume.com/api-stash/index.php?league=heist&tab=1&tabIndex=${i}&accountName=Toofi`, {
      method: "GET"});
    grabJson = await grab.json();
    console.log(grabJson);
    allItems = allItems.concat(grabJson.items);

  }
  console.log(allItems);
};

console.log(mockJson);

//to get all the items of all the stashes in one JSON. Be aware of the GGG's rate limit. The 'test.json' file is a mock generated by the fetch for dev purposes.
// getAllItems()