import * as connect from './modules/connect.js';
console.log(mockJson);
for (let i = 1; i < 38; i++){
  var inventory = mockJson.filter((element) => element.inventoryId == 'Stash1');
  console.log(inventory);
}


// mockJson.forEach(element => {
//   console.log(element.inventoryId);
// });

// for(let element in mockJson) {
//   console.log(mockJson[element]);
// }

//to get all the items of all the stashes in one JSON. Be aware of the GGG's rate limit. The 'test.json' file is a mock generated by the fetch for dev purposes.
// connect.getAllItems()